#!/bin/bash

source .3bs/*essential.sh

here=$(readlink -f $(dirname ${BASH_SOURCE[0]}))

_DisplayTrace "Retrieving dependencies..."
_DisplayTrace "Arguments: $@"

rm -fr Dependency/

ConsoleCommands=$(
    cat deps.json | handlerpath=".3bs/Asset" \
        $here/ResolveConsoleCommands
)

bash -c "$ConsoleCommands"

for Dependency in `ls -A Dependency/`
do
    # If a handler exists, it would be at this path
    echo dependency is: $Dependency
    handler="Tool/Handler/Dependency/$Dependency"

    # Create a temporary directory for a handler to transfer files to & from
    tmpdir=$(mktemp -qdt 3bs.dependency.handler.Init.$Dependency.XXXXXX)
    test -z "$tmpdir" && _DisplayError "temporary directory has not been set!\n\r\tExitting!" && exit 1

    # If a handler exists, run its Init function
    test -f "$handler" && bash "$handler" _Init "$tmpdir"
done